---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../dt/bgp/networking

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

resources:
  - nncp/values.yaml
  - metallb_bgppeers.yaml
  - ocp_networks_netattach.yaml

patches:
  # Add BGPPeer to BGPAdvertisement
  - target:
      kind: BGPAdvertisement
    patch: |-
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-3-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-3-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-4-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-4-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-5-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-5-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-6-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-6-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-7-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-7-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-8-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-8-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-9-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-9-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-10-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-10-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-11-0
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-11-1
      - op: add
        path: /spec/peers/-
        value: bgp-peer-node-12-0
  - target:
      kind: NetworkAttachmentDefinition
      labelSelector: "osp/net-attach-def-type=bgp"
    path: ocp_network_template.yaml

  # All L2Advertisements are removed
  - target:
      kind: L2Advertisement
    patch: |-
      kind: L2Advertisement
      metadata:
        name: .*
      $patch: delete

replacements:
  # BGP peer IP addresses
  # node3
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-3-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-3-1
        fieldPaths:
          - spec.peerAddress
  # node4
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_4.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-4-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_4.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-4-1
        fieldPaths:
          - spec.peerAddress
  # node5
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_5.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-5-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_5.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-5-1
        fieldPaths:
          - spec.peerAddress
  # node6
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_6.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-6-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_6.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-6-1
        fieldPaths:
          - spec.peerAddress
  # node7
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_7.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-7-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_7.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-7-1
        fieldPaths:
          - spec.peerAddress
  # node8
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_8.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-8-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_8.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-8-1
        fieldPaths:
          - spec.peerAddress
  # node9
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_9.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-9-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_9.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-9-1
        fieldPaths:
          - spec.peerAddress
  # node10
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_10.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-10-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_10.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-10-1
        fieldPaths:
          - spec.peerAddress
  # node11
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_11.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-11-0
        fieldPaths:
          - spec.peerAddress
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_11.bgp_peers.1
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-11-1
        fieldPaths:
          - spec.peerAddress
  # node12
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_12.bgp_peers.0
    targets:
      - select:
          kind: BGPPeer
          name: bgp-peer-node-12-0
        fieldPaths:
          - spec.peerAddress

  # BGP NetworkAttachmentDefinition customization
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.bgp.net-attach-def.node12
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: bgpnet-worker-9
        fieldPaths:
          - spec.config
