---
apiVersion: v1
kind: Secret
metadata:
  name: cinder-volume-nfs-secrets
type: Opaque
stringData:
  cinder-volume-nfs-secrets: |
    [nfs]
    nas_host=192.168.122.1
    nas_share_path=/data/cinder
