---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  preserveJobs: false
  cinderVolumes:
    ontap-nfs:
      customServiceConfig: |
        [ontap]
        volume_backend_name=nfs
        volume_driver=cinder.volume.drivers.nfs.NfsDriver
        nfs_snapshot_support=true
        nas_secure_file_operations=false
        nas_secure_file_permissions=false
      ontap-cinder-secrets.conf: |
        [ontap]
        nas_host = 192.168.122.1
        nas_share_path = /data/cinder
  glance:
    customServiceConfig: |
      [DEFAULT]
      enabled_backends = default_backend:file
      [glance_store]
      default_backend = default_backend
      [default_backend]
      filesystem_store_datadir = /var/lib/glance/images
    default:
      replicas: 1
      type: single
    extraMounts:
      - extraVol:
          - extraVolType: Nfs
            mounts:
              - mountPath: /var/lib/glance/images
                name: nfs
            volumes:
              - name: nfs
                nfs:
                  path: "/data/glance"
                  server: 192.168.122.1
