---
apiVersion: v1
kind: ConfigMap

metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  preserveJobs: false
  cinderVolumes:
    ontap-iscsi:
      customServiceConfig: |
        [ontap]
        volume_backend_name=ontap
        volume_driver=cinder.volume.drivers.netapp.common.NetAppDriver
        netapp_server_hostname=_replaced_
        netapp_server_port=80
        netapp_storage_protocol=iscsi
        netapp_storage_family=ontap_cluster
        consistencygroup_support=True
      networkAttachments:
        - storage
      customServiceConfigSecrets:
        - cinder-volume-ontap-secrets
  cinder-volume-ontap-secrets: |
    [ontap]
    netapp_login = _replaced_
    netapp_password = _replaced_
    netapp_vserver = _replaced_
  cinderBackup:
    customServiceConfig: |
      [DEFAULT]
      backup_driver = cinder.backup.drivers.swift.SwiftBackupDriver
    replicas: 1

  glance:
    customServiceConfig: |
      [DEFAULT]
      debug=True
      enabled_backends = default_backend:swift

      [glance_store]
      default_backend = default_backend

      [default_backend]
      swift_store_create_container_on_put = True
      swift_store_auth_version = 3
      swift_store_auth_address = {{ .KeystoneInternalURL }}
      swift_store_endpoint_type = internalURL
      swift_store_user = service:glance
      swift_store_key = {{ .ServicePassword }}

    default:
      replicas: 1

  swift:
    enabled: true


  octavia:
    enabled: false
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    octaviaAPI:
      networkAttachments:
        - internalapi
    octaviaHousekeeping:
      networkAttachments:
        - octavia
    octaviaHealthManager:
      networkAttachments:
        - octavia
    octaviaWorker:
      networkAttachments:
        - octavia

  ovn:
    ovnController:
      nicMappings:
        datacentre: ocpbr
        octavia: octbr

  neutron:
    customServiceConfig: |
      [DEFAULT]
      vlan_transparent = true
      agent_down_time = 600
      router_distributed = true
      router_scheduler_driver = neutron.scheduler.l3_agent_scheduler.ChanceScheduler
      allow_automatic_l3agent_failover = true
      debug = true

      [agent]
      report_interval = 300

      [database]
      max_retries = -1
      db_max_retries = -1

      [keystone_authtoken]
      region_name = regionOne
      memcache_use_advanced_pool = True

      [oslo_messaging_notifications]
      driver = noop

      [oslo_middleware]
      enable_proxy_headers_parsing = true

      [oslo_policy]
      policy_file = /etc/neutron/policy.yaml

      [ovs]
      igmp_snooping_enable = true

      [ovn]
      ovsdb_probe_interval = 60000
      ovn_emit_need_to_frag = true

      [ml2]
      type_drivers = geneve,vxlan,vlan,flat
      tenant_network_types = geneve,flat,vlan
