---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../dt/pidone/edpm/deployment

resources:
  - values.yaml


patches:
  - target:
      kind: OpenStackDataPlaneDeployment
      name: edpm-deployment
    patch:
      - op: add
        path: /spec/nodeTemplate/ansible/ansibleVars/edpm_extra_mounts
        value:
          - fstype: nfs4
            name: /var/lib/nova/instances
            opts: context=system_u:object_r:nfs_t:s0
            path: /data/nova
